---
abstract: 'PSGI handler for HTML::Mason'
author:
  - 'Ask Bjørn Hansen <ask@develooper.com>'
build_requires:
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Mason-PSGIHandler
requires:
  CGI::PSGI: 0
  HTML::Mason: 0
resources:
  bugtracker: http://github.com/abh/HTML-Mason-PSGIHandler/issues
  homepage: http://search.cpan.org/dist/HTML-Mason-PSGIHandler/
  repository: http://github.com/abh/HTML-Mason-PSGIHandler
version: 0.50
